default: &default
  adapter: postgresql
  username: adamzima
  password: ''
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: tweety_dev

test:
  <<: *default
  database: tweety_test
